pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = "https://maven.fabricmc.net/" }
        maven { url = "https://maven.architectury.dev/" }
        maven { url = "https://maven.neoforged.net/releases/" }
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven { url = "https://hub.spigotmc.org/nexus/content/repositories/snapshots/" }
        maven { url = "https://libraries.minecraft.net/" }
        maven { url = "https://maven.fabricmc.net/" }
        maven { url = "https://maven.architectury.dev/" }
        maven { url = "https://maven.neoforged.net/releases/" }
    }
}

rootProject.name = "ZstdNet"

include "core"
include "spigot"
include "mod-common"
include "fabric"
include "neoforge"
